apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: pet-store
  description: A collection of all Backstage example entities, INCLUDING users, groups, and templates
spec:
  targets:
    - ./apis/petstore-api.yaml
    
